# Generated by Django 5.1.4 on 2024-12-11 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
